# docker-compose.prod.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Use the production Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - ./logs:/var/log/nginx
