# docker-compose.dev.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use the development Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Mount local files for live-reloading
      - /app/node_modules  # Avoid overwriting node_modules in the container
    environment:
      - NODE_ENV=development
    command: npm start
    restart: unless-stopped
